// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "d6dc36d6-baae-40ea-b99d-990da0c69020";

const char SSID[]               = "BigLukeNetwork";    // Network SSID (name)
const char PASS[]               = "lukethedog";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "QrJP#99z0DhocOotYKJrimHKd";    // Secret device password


float pow0;
float pow1;
float pow2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(pow0, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(pow1, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(pow2, READ, 10 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
